--Creation des roles de notre bd
CREATE ROLE NETFLIX_READER_ROLE;
CREATE ROLE NETFLIX_CINEASTE_ROLE;
CREATE ROLE NETFLIX_STATISTICIEN_ROLE;

--Ajout de différents provilèges aux roles
--donne le privilège pour se connecter et interroger la base
GRANT CREATE SESSION TO NETFLIX_READER_ROLE;
GRANT CREATE SESSION TO NETFLIX_CINEASTE_ROLE;
GRANT CREATE SESSION TO NETFLIX_STATISTICIEN_ROLE;

--Donne la possiblité de select sur nomoeuvre et oeuvre a netflix reader role
GRANT SELECT ON NOM_OEUVRE TO NETFLIX_READER_ROLE;
GRANT SELECT ON OEUVRE TO NETFLIX_READER_ROLE;
--Donne la possiblité de lancer la procedure ajout oeuvre a netflix cineaste role
GRANT EXECUTE ON procedure_ajoutOeuvre TO NETFLIX_CINEASTE_ROLE;
--Donne la possiblité de lancer les procedure tempsVisionnagePourCompte et calculMoyenne a netflix statisticien role
GRANT EXECUTE ON TempsVisionnagePourCompte TO NETFLIX_STATISTICIEN_ROLE;
GRANT EXECUTE ON CalculMoyenne TO NETFLIX_STATISTICIEN_ROLE;


--Creation des user
CREATE USER NETFLIX_ADMIN IDENTIFIED BY passwordsolide QUOTA UNLIMITED ON USERS;
CREATE USER ELEVEDEL3 IDENTIFIED BY mdptresdur QUOTA UNLIMITED ON USERS;
CREATE USER STEVEN_SPIELBERG IDENTIFIED BY monfilmpref QUOTA UNLIMITED ON USERS;
CREATE USER MICHEL_VOLLE IDENTIFIED BY lemotdepassedesstatisticiens QUOTA UNLIMITED ON USERS;

GRANT DBA TO NETFLIX_ADMIN; --donne le rôle dba à NETFLIX_ADMIN
GRANT NETFLIX_READER_ROLE TO ELEVEDEL3; --donne le rôle READER à ELEVEDEL3
GRANT NETFLIX_CINEASTE_ROLE TO STEVEN_SPIELBERG; --donne le rôle CINEASTE à STEVEN_SPIELBERG
GRANT NETFLIX_STATISTICIEN_ROLE TO MICHEL_VOLLE; --donne le rôle STATISTICIEN à MICHEL_VOLLE